/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IERCFull20, IERCFull20Interface } from "../IERCFull20";
import { _abi } from '../abi/IERCFull20ABI';


export class IERCFull20__factory {
  static readonly abi = _abi;
  static createInterface(): IERCFull20Interface {
    return new utils.Interface(_abi) as IERCFull20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERCFull20 {
    return new Contract(address, _abi, signerOrProvider) as IERCFull20;
  }
}
