/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISupply, ISupplyInterface } from "../ISupply";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_admins",
        type: "address[]",
      },
    ],
    name: "addAdmins",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_admins",
        type: "address[]",
      },
    ],
    name: "removeAdmins",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "safeTokenTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISupply__factory {
  static readonly abi = _abi;
  static createInterface(): ISupplyInterface {
    return new utils.Interface(_abi) as ISupplyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISupply {
    return new Contract(address, _abi, signerOrProvider) as ISupply;
  }
}
