/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IVesting, IVestingInterface } from "../IVesting";
import { _abi } from "../abi/IVestingABI";

export class IVesting__factory {
  static readonly abi = _abi;
  static createInterface(): IVestingInterface {
    return new utils.Interface(_abi) as IVestingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVesting {
    return new Contract(address, _abi, signerOrProvider) as IVesting;
  }
}
